# SConstruct for share/man

#-------------------------------------------------------------------------------
# Copyright (C) 2013
#
# This file is part of ezilla.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>
#
# Author: Chang-Hsing Wu <hsing _at_ nchc narl org tw>
#         Serena Yi-Lun Pan <serenapan _at_ nchc narl org tw>
#         Hsi-En Yu <yun _at_  nchc narl org tw>
#         Hui-Shan Chen  <chwhs _at_ nchc narl org tw>
#         Kuo-Yang Cheng  <kycheng _at_ nchc narl org tw>
#         CHI-MING Chen <jonchen _at_ nchc narl org tw>
#-------------------------------------------------------------------------------
#

Import('env')

po_bld = Builder(action = 'share/scons/po2json.rb $SOURCE > $TARGET',
                 suffix = '.js',
                 src_suffix = '.po')

env.Append(BUILDERS = {'Po' : po_bld})

env.Po('ca.po')
env.Po('cs_CZ.po')
env.Po('da.po')
env.Po('de.po')
env.Po('el_GR.po')
env.Po('en_US.po')
env.Po('es_ES.po')
env.Po('fa_IR.po')
env.Po('fr_FR.po')
env.Po('it_IT.po')
env.Po('nl_NL.po')
env.Po('pl.po')
env.Po('pt_PT.po')
env.Po('pt_BR.po')
env.Po('ru_RU.po')
env.Po('sk_SK.po')
env.Po('zh_TW.po')
env.Po('zh_CN.po')

